feat: Сделан компонент ProjectCard
SergeiKachenia/Lorem-Ipsum-Team-landing pull request #13
Opened 2022-12-17 20:31 UTC by Danxay

1. Сделан компонент ProjectCard и адаптив к нему
2. Изменена типизация для Stack
3. Добавлены моки с краткой и полной информацией о проектах
4. Добавлены Redux Toolkit и react-redux
5. Создан Store и projectsSlice
6. Добавлено получение проектов из state

2022-12-17 21:23 UTC, AnimeLore requested changes

2022-12-17 21:23 UTC, AnimeLore commented on src/constants/projects.ts
> +      name: 'Афанасьев Артем',
Если данные нормализуются, то тогда, думаю, тут не помешал бы id.

2022-12-17 21:23 UTC, AnimeLore commented on src/types/IProject.ts
> +  name: string;
Если в моке нормализация - думаю нужен id.

2022-12-17 21:23 UTC, AnimeLore commented on src/components/ProjectCards/ProjectCard/ProjectCard.tsx
> +          />{' '}
У блока address (класс .author) стоит flex, думаю стоит вместо пробела использовать gap.

2022-12-17 21:23 UTC, AnimeLore commented on src/components/ProjectCards/ProjectCards.tsx
> +    <div className={styles.wrapper}>
wrapper, судя по css, вообще не нужен.

2022-12-18 07:55 UTC, SergeiKachenia requested changes

2022-12-18 07:55 UTC, SergeiKachenia commented on src/components/ProjectCards/ProjectCard/ProjectCard.tsx
> +import defaultAvatar from '../../../assets/images/avatar.png';
Точки относительного пути не нужны

2022-12-18 07:55 UTC, SergeiKachenia commented on src/components/StackLabel/StackLabel.tsx
> +import { IStackLabelProps } from '../../types/IStack';
Тоже самое, точки не нужны

2022-12-18 08:28 UTC, AnimeLore approved these changes

2022-12-18 09:05 UTC, SergeiKachenia approved these changes

2022-12-18 09:06 UTC, merged